Square.UI/Controllers/AdController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

using Newtonsoft.Json;
using Square.Common.Entities.Ad;
using Square.Common.Entities.Common;
using Square.Services.Contracts.Services;
using Square.UI.Mappers;
using Square.UI.Models;
using Square.UI.Models.AccountEntityModel;
using Square.UI.Models.AdEntityModels;

namespace Square.UI.Controllers
{
    /// <summary>
    /// Контроллер, для работы с объявлениями.
    /// </summary>
    [RoutePrefix("ads")]
    public class AdController : Controller
    {
        private readonly IAdService _adService;
        private readonly ICityService _cityService;
        private readonly IUserService _userService;

        public AdController(
            IAdService adService,
            ICityService cityService,
            IUserService userService)
        {
            _adService = adService;
            _cityService = cityService;
            _userService = userService;
        }

        /// <summary>
        /// Возвращает Топ-20 объявлений на странице (по фильтрам).
        /// </summary>
        [HttpGet]
        [Route("")]
        public async Task<ActionResult> Index(
            int page = 1,
            int cityID = 0,
            int districtID = 0,
            int priceFrom = 0,
            int priceTo = 0,
            int roomsCount = 0,
            string search = null,
            int orderedBySelected = 0,
            string roomsCountString = null)
        {
        
            var roomsCountSelect = new List<string>();
            if (roomsCountString != null)
            {
                roomsCountSelect = roomsCountString.Split('|').ToList();
            }

            var userID = 0;
            if (User.Identity.IsAuthenticated)
            {
                var user = await _userService.GetUserByPhoneNumberAsync(User.Identity.Name);
                userID = user.UserID;
            }

            var filter = new AdFilter
            {
                CityID = cityID,
                DistrictID = districtID,
                PriceFrom = priceFrom,
                PriceTo = priceTo,
                RoomsCount = roomsCount,
                Search = search,
                OrderedBy = orderedBySelected,
                RoomsCountSelect = roomsCountSelect,
                UserID = userID
            };

            var take = 24;

            var adDataTable = await _adService.GetAdsAsync(filter, page, take);

            var adModels = adDataTable
                .Items
                .Select(AdMapper.MapToAdModel)
                .ToList();

            var cities = await _cityService.GetCitiesAsync();

            var cityModels = cities
                .Select(CityMapper.MapToCityModel)
                .ToList();

            var pager = new Pager(adDataTable.Total, page, take);

            FillLocationInfoForAds(adModels, cityModels);

            var adDataTableModel = GetAdDateTableModel(
                adModels,
                cityModels,
                page,
                cityID,
                districtID,
                priceFrom,
                priceTo,
                roomsCount,
                search,
                adDataTable.Total,
                orderedBySelected,
                pager,
                roomsCountSelect);

            return View(adDataTableModel);
        }

        /// <summary>
        /// Возвращает Топ-20 объявлений из архива на странице (по фильтрам).
        /// </summary>
        [HttpGet]
        public async Task<ActionResult> Archive(
            int page = 1,
            int cityID = 0,
            int districtID = 0,
            int priceFrom = 0,
            int priceTo = 0,
            int roomsCount = 0,
            string search = null,
            int orderedBySelected = 0,
            string roomsCountString = null)
        {

            var roomsCountSelect = new List<string>();
            if (roomsCountString != null)
            {
                roomsCountSelect = roomsCountString.Split('|').ToList();
            }

            var filter = new AdFilter
            {
                CityID = cityID,
                DistrictID = districtID,
                PriceFrom = priceFrom,
                PriceTo = priceTo,
                RoomsCount = roomsCount,
                Search = search,
                OrderedBy = orderedBySelected,
                RoomsCountSelect = roomsCountSelect
            };

            var take = 21;

            var adDataTable = await _adService.GetAdsFromArchiveAsync(filter, page, take);

            var adModels = adDataTable
                .Items
                .Select(AdMapper.MapToAdModel)
                .ToList();

            var cities = await _cityService.GetCitiesAsync();

            var cityModels = cities
                .Select(CityMapper.MapToCityModel)
                .ToList();

            var pager = new Pager(adDataTable.Total, page, take);

            FillLocationInfoForAds(adModels, cityModels);

            var adDataTableModel = GetAdDateTableModel(
                adModels,
                cityModels,
                page,
                cityID,
                districtID,
                priceFrom,
                priceTo,
                roomsCount,
                search,
                adDataTable.Total,
                orderedBySelected,
                pager,
                roomsCountSelect);


            return View(adDataTableModel);
        }

        [HttpGet]
        public async Task<ActionResult> AdCommerce()
        {
            return View();
        }

        /// <summary>
        /// Возвращает объявление по идентификатору.
        /// </summary>
        [HttpGet]
        public async Task<ActionResult> GetAdInfoByIdAsync(int adId)
        {
            if (User.IsInRole("Guest"))
            {
                return RedirectToAction("Index");
            }

            var ad = await _adService.GetAdByIDAsync(adId);

            await _adService.UpdateViewsCountAsync(adId);

            if (User.Identity.IsAuthenticated && User.IsInRole("User"))
            {
                var user = await _userService.GetUserByPhoneNumberAsync(User.Identity.Name);
                await _userService.UpdateFreeViewsAsync(user.UserID);
            }

            var adModel = AdMapper.MapToAdModel(ad);
            
            var similarAdModels = ad.SimilarAds.Select(AdMapper.MapToAdModel).ToList();

            adModel.SimilarAds = similarAdModels;


            var cities = await _cityService.GetCitiesAsync();

            var cityModels = cities
                .Select(CityMapper.MapToCityModel)
                .ToList();

            FillLocationInfoForAds(new List<AdModel> { adModel }, cityModels);


            if (adModel.IsAvito)
            {
                var ph = adModel.Phone.PhoneNumber;
                ph = ph.Insert(2, "(");
                ph = ph.Insert(6, ")");
                ph = ph.Insert(10, "-");
                ph = ph.Insert(13, "-");

                adModel.Phone.PhoneNumber = ph;
            }

            return View("Info", adModel);
        }

        /// <summary>
        /// Возвращает объявление из архива по идентификатору.
        /// </summary>
        [Authorize]
        [HttpGet]
        public async Task<ActionResult> GetAdArchiveInfoByIdAsync(int adId)
        {
            var ad = await _adService.GetAdArchiveByIDAsync(adId);

            await _adService.UpdateViewsCountAsync(adId);

            var adModel = AdMapper.MapToAdModel(ad);

            var similarAdModels = ad.SimilarAds.Select(AdMapper.MapToAdModel).ToList();

            adModel.SimilarAds = similarAdModels;


            var cities = await _cityService.GetCitiesAsync();

            var cityModels = cities
                .Select(CityMapper.MapToCityModel)
                .ToList();

            FillLocationInfoForAds(new List<AdModel> { adModel }, cityModels);

            return View("InfoArchive", adModel);
        }


        /// <summary>
        /// Возвращает окно с подтверждением об удалении объявления.
        /// </summary>
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<ActionResult> Delete(int adId)
        {
            await _adService.DeleteAdByIDAsync(adId);

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Возвращает страницу для добавления заявки на объявление.
        /// </summary>
        [HttpGet]
        public async Task<ActionResult> AddRequest()
        {
            var cities = await _cityService.GetCitiesAsync();

            var cityModels = cities
                .Select(CityMapper.MapToCityModel)
                .ToList();

            var adModel = new AdModel
            {
                Cities = cityModels,
                Phone = new PhoneModel(),
                ComfortModel = new ComfortModel(),
                LocationInfo = new AdLocationInfoModel(),
                RoomsCountModel = new RoomsCountModel
                {
                    One = true
                }
            };

            return View("AddRequest", adModel);
        }

        /// <summary>
        /// Добавляет новое объявление.
        /// </summary>
        [Authorize]
        [HttpPost]
        public async Task<ActionResult> AddRequest(AdModel adModel)
        {
            var errors = new List<ErrorTypeEnum>();


            if (!ModelState.IsValid)
            {
                var cities = await _cityService.GetCitiesAsync();

                var cityModels = cities
                    .Select(CityMapper.MapToCityModel)
                    .ToList();

                adModel.Cities = cityModels;

                if (!IsRoomsCountNotNull(adModel.RoomsCountModel))
                {
                    errors.Add(ErrorTypeEnum.RoomsCountNull);

                    adModel.Errors = errors;

Square.UI/Controllers/PriceController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

using Square.Common.Entities.Portal;
using Square.Services.Contracts.Services;
using Square.UI.Mappers;
using Square.UI.Models.AccountEntityModel;

namespace Square.UI.Controllers
{
    /// <summary>
    /// Контроллер, для работы с подписками.
    /// </summary>
    [Route("subscriptions")]
    public class PriceController : Controller
    {
        private readonly IUserService _userService;

        public PriceController(IUserService userService)
        {
            _userService = userService;
        }

        /// <summary>
        /// Возвращает страницу с подписками.
        /// </summary>
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var subscriptions = _userService.GetSubscriptionsAsync();

            var subscriptionModels = subscriptions
                .Select(UserMapper.MapToSubscriptionModel)
                .OrderBy(subscriptionModel => subscriptionModel.SortOrder)
                .ToList();

            if (User.Identity.IsAuthenticated)
            {
                var user = await _userService.GetUserByPhoneNumberAsync(User.Identity.Name);

                var subscriptionInfo = await _userService.GetUserCurrentSubscriptionAsync(user.UserID);
                if (subscriptionInfo != null)
                {
                    var subscriptionInfoModel = subscriptionModels.FirstOrDefault(subscription =>
                        subscription.SubscriptionID == subscriptionInfo.SubscriptionID);
                    if (subscriptionInfoModel != null)
                    {
                        subscriptionInfoModel.ConnectedSubscription =
                            new Tuple<int?, DateTime>(user.UserID, subscriptionInfo.EndDate.GetValueOrDefault());

                        return View("ConnectedSubscription", subscriptionModels);
                    }
                }
            }


            return View(subscriptionModels);
        }

        /// <summary>
        /// Возвращает страницу, для оплаты подписки.
        /// </summary>
        [HttpGet]
        public async Task<ActionResult> Pay(int subscribtionID = 1)
        {
            var subscriptionInfo = _userService
                .GetSubscriptionsAsync()
                .FirstOrDefault(subscription => subscription.SubscriptionID == subscribtionID);

            var userModel = new UserModel();
            var user = new User();

            if (User.Identity.IsAuthenticated)
            {
                user = await _userService.GetUserByPhoneNumberAsync(User.Identity.Name);
                userModel = UserMapper.MapToUserModel(user);
            }
        

            var subscriptionInfoModel = UserMapper.MapToSubscriptionModel(subscriptionInfo);

            var subscriptionModel = new Models.AdEntityModels.SubscriptionModel
            {
                UserInfo = userModel,
                SubscriptionInfo = subscriptionInfoModel,
                TotalPrice = subscriptionInfo.Price,
                OrderNumber = user != null ? user.OrderNumber : 1
            };

            return View(subscriptionModel);
        }

        [HttpGet]
        public async Task<ActionResult> PayConnect(int subscriptionID, int userID)
        {
            var subscription = new Subscription
            {
                Type = MapToSubscriptionEnum(subscriptionID),
                UserID = userID
            };

            await _userService.ConnectSubscriptionToUserAsync(subscription);

            return View("SubscriptionConnectedNotify");
        }

        [HttpGet]
        public async Task<ActionResult> PayConnectError()
        {
            return View("SubscriptionConnectedErrorNotify");
        }

        private static SubscriptionEnum MapToSubscriptionEnum(int subscriptionID)
        {
            switch (subscriptionID)
            {
                case 1: return SubscriptionEnum.Base;
                case 2: return SubscriptionEnum.Optimal;
                case 3: return SubscriptionEnum.Maximal;

                default: return 0;
            }
        }
    }
}

Square.UI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    @Styles.Render("~/Content/carousel.css")
}

<style>
    .jumbotron {
        height: 250px;
    }

    .jumbotron {
        position: relative;
        overflow: hidden;
        background-color: black;
    }

    .jumbotron video {
        position: absolute;
        z-index: 1;
        top: 0;
        width: 100%;
        height: 100%;
        /*  object-fit is not supported on IE  */
        object-fit: cover;
        opacity: 0.5;
    }

    .jumbotron .container {
        z-index: 2;
        position: relative;
    }
</style>

<div class="jumbotron jumbotron-fluid">
    <video  class="video-fluid" playsinline autoplay loop muted>
        <source src="https://ros-rielt.ru/video/aboutus.mp4" type="video/mp4" />
    </video>
    <div class="container text-white">

        <h2 class="display-4" style="font-size: 45px;">Ros-Rielt</h2>
     
        <p class="lead">
          Аренда квартир от собственников
        </p>
    </div>
</div>
<main role="main">
    <div class="container marketing">
        <!-- Three columns of text below the carousel -->
        <div class="row">
            <div class="col-lg-4">
                <img class="rounded-circle" src="~/Images/daniil2.jpg" alt="Generic placeholder image" style=" object-fit: cover;" width="140" height="140">
                <h2>Главный разработчик</h2>
                <p>Я Даниил. Отвечаю за команду разработки и поддержки веб-сайта "Ros-Rielt". Мы стараемся разрабатывать удобный сервис, чтобы Вам было максимально комфортно. По вопросам обращайтесь на Email: <br /> danyfromsaratov@gmail.com</p>
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <img class="rounded-circle" src="~/Images/kamila.jpg" alt="Generic placeholder image" style=" object-fit: cover;" width="140" height="140">
                <h2>Администратор</h2>
                <p>Меня зовут Камелия. Я являюсь Администратором веб-сайта "Ros-Rielt". По всем техническим вопросам можете обратиться по телефону: <br /> 8 (965) 884 52 38.</p>
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <img class="rounded-circle" src="~/Images/maria.jpg" alt="Generic placeholder image" style=" object-fit: cover;" width="140" height="140">
                <h2>Специалист по недвижимости</h2>
                <p>
                    Привет! Я Мария, специалист по недвижимости в компании "Ros-Rielt". Я и моя команда занимаемся поиском квартир, отбором собственников,
                    а также помогаем в заселении "до двери". Со мной можно связаться по телефону: <br /> 8 (965) 884 52 39. <br /> Буду рада Вам помочь!
                </p>
            </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->
        <hr class="featurette-divider">
        <div class="row featurette">
            <div class="col-md-5">
                <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="500x500" src="~/Images/about221.jpg" style="width: 500px; height: 400px;  object-fit: cover;" data-holder-rendered="true">
            </div>
            <div class="col-md-7">
                <h2 class="featurette-heading">Кто мы!?</h2>
                <p class="lead">
                    Мы команда молодых и харизматичных специалистов с огромным желанием сделать Вашу жизнь проще.
                    Наша цель - быстро и эффективно предоставить необходимые ресурсы для поиска жилья.
                    Всего лишь по цене обеда в МакДональдс Вы можете получить полный доступ ко всем проверенным контактам.
                    <br /><br />Мы уверены, что Вы найдете то, что ищите!
                </p>
            </div>
        </div>


        <hr class="featurette-divider">
        <div class="row featurette">
            <div class="col-md-5 order-md-2">
                <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="500x500" src="~/Images/aboutus1.jpg" style="width: 500px; height: 400px;  object-fit: cover;">
            </div>
            <div class="col-md-7 order-md-1">
                <h2 class="featurette-heading">Чем мы занимаемся?</h2>
                <br />
                <p class="lead">
                    ✅ Работаем официально<br><br>

                    ✅ Занимаемся арендой недвижимости и делаем это качественно<br><br>

                    ✅ Работаем с собственниками<br><br>

                    ✅ Предоставляем минимальные затраты на поиск жилья или помещения<br><br>

                    ✅ Добавляем несколько сотен новых объектов в неделю
                </p>
            </div>
        </div>

        <!-- START THE FEATURETTES -->
        <hr class="featurette-divider">
        <div class="row featurette">
            <div class="col-md-5">
                <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="500x500" src="~/Images/run1.jpg" style="width: 500px; height: 400px;  object-fit: cover;" data-holder-rendered="true">
            </div>
            <div class="col-md-7">
                <h2 class="featurette-heading">Быстро</h2>
                <p class="lead">
                    Вы можете выбрать подходящее для вас жильё за несколько минут, не выходя из дома, без посещения офиса. Наш сайт обновляется модераторами каждый день. Сервис доступен для пользователей 24/7.
                </p>
            </div>
        </div>
        <hr class="featurette-divider">
        <div class="row featurette">
            <div class="col-md-7 order-md-1">
                <h2 class="featurette-heading">Экономно</h2>
                <p class="lead">Преимущество базы "Ros-Rielt" в том, что вам не нужно переплачивать посредникам, все объекты от собственников вы сможете найти здесь.</p>
            </div>
            <div class="col-md-5 order-md-2">
                <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="500x500" src="~/Images/saving.jpg" style="width: 500px; height: 400px;  object-fit: cover;">
            </div>
        </div>
        <hr class="featurette-divider">

        <div class="row featurette">
            <div class="col-md-5">
                <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="500x500" src="~/Images/quality1.jpg" style="width: 500px; height: 400px;  object-fit: cover;">
            </div>
            <div class="col-md-7">
                <h2 class="featurette-heading">Качественно</h2>
                <p class="lead">
                    На нашем сайте вы можете быть уверены в качестве обслуживания. Вы можете получить бесплатную консультацию. Отзывчивая администрация и специалист по недвижимости ответят на все ваши вопросы. Мы ценим своих клиентов и стремимся предоставить лучший сервис.
                </p>
            </div>
        </div>
        <hr class="featurette-divider">

    </div><!-- /.container -->
    </main>

Square.UI/Views/Home/FreeAdd.cshtml
@{
    ViewBag.Title = "FreeAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    @@media only screen and (max-width: 800px) {
        .my-content: margin-bottom: 250px;
    }
</style>
<div class="container my-5 z-depth-1">
    <section class="dark-grey-text">

        <div class="row pr-lg-5">
            <div class="col-md-7 mb-4">

                <div class="view">
                    <img src="~/Images/adF.jpg" class="img-fluid" alt="smaple image" />
                </div>

            </div>
            <div class="col-md-5 d-flex align-items-center my-content">
                <div>

                    <h3 class="font-weight-bold mb-4">Разместить объявлениe!</h3>

                    <p>
                        Разместите объявление абсолютно бесплатно. Наши модераторы постараются как можно быстрее обработать Вашу заявку
                        и добавить объявление на сайте Ros-Rielt.
                    </p>

                    <a class="btn btn-light-blue btn-rounded mx-0" style="margin-bottom: 50px;" href=@Url.Action("AddRequest", "Ad")>Разместить объявление</a>
                </div>
            </div>
        </div>
    </section>

</div>

Square.UI/Views/Home/GetOrderedCalls.cshtml
@model IEnumerable<string>
@{
    ViewBag.Title = "GetOrderedCalls";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container" style="margin-top: 50px;">
    <h2>Заказанные звонки:</h2>
    <br />
    <div class="row">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Номер Телефона</th>
                <th scope="col">Операции</th>
            </tr>
            </thead>
            <tbody>    
            @{ var count = 1; }
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@count</th>
                    <td>@item</td>
                    <td> <a href="@Url.Action("RemoveCall", "Home", new {phoneNumber = item})"class="btn btn-outline-success">Ответил</a></td>
                </tr>

                count++;
            }
            </tbody>
        </table>
    </div>
</div>

Square.UI/Views/Home/Index.cshtml
@{
    <link href="~/Content/HomePage/Home.css" rel="stylesheet" />
    <link href="~/Content/Home/sd.css" rel="stylesheet" />
    <link href="~/Content/Home.css" rel="stylesheet" />
}

<style>
    .actionbtns a:hover {
        color: white;
    }
</style>
<div class="container " style="color: black;  margin-bottom: 20px;">
    <div class="row" style="margin-top:20px; margin-left: 10px;">
        <div class="col-md-6 homeTitle">
            <h1 style=" margin-top: 100px;">Аренда</h1>
            <h1>недвижимости</h1>
            <h1>без посредников</h1>
            <h1>в Москве</h1>
        </div>
        <div class="col-md-6 homeGif" style="width: 100%;">
            <img style="width: 100%;" src="https://media.giphy.com/media/8Z4hnKjmF0UiQ/giphy.gif">
        </div>
    </div>
    <div class="form-row actionbtns" style="">
        <div class="col-md-3 text-box3">
            <a href=@Url.Action("Index", "Price") class="btnm btn-white btn-animate" style="font-weight: bold; font-size: 18px;"><img class="icon" style="width: 40px; height: 40px; margin-right: 10px;" src="~/Images/bid.png" />Подписки</a>
        </div>
        <div class="col-md-3  text-box3">
            <a href=@Url.Action("Comments", "Home") class="btnm btn-white btn-animate" style="font-weight: bold; font-size: 18px;"><img class="icon" style="width: 40px; height: 40px; margin-right: 10px;" src="~/Images/comment.png" />Отзывы</a>
        </div>
        <div class="col-md-4 text-box3">
            <a href=@Url.Action("DownloadFile", "Home") class="btnm btn-white btn-animate" style="font-weight: bold; font-size: 18px;"><img class="icon" style="width: 40px; height: 40px; margin-right: 10px;" src="~/Images/file.png" />Договор аренды</a>
        </div>
    </div>
    <div class="card-deck mb-3 text-center homecontainer" style="margin-top: 80px;">
        <div class="card mb-4 box-shadow mylink card-1 myLink1" style="min-width: 280px;background-color: rgb(77, 119, 202); width: 300px; cursor: pointer">
            <a  href=@Url.Action("Index", "Ad")>
                <div class="card-body" style="color: white;">
                    <span style="float: left; margin-bottom: 20px; margin-left: 0; font-size: 24px; font-weight: bold; text-align: left;">Аренда недвижимости</span>
                    <span style="float: left; font-size: 21px; margin-left: 0; text-align: left; margin-bottom: 5px;">Аренда недвижимости от собственника, без посредников и без переплат.</span>
                </div>
                <p >
                    <img class="icon" style="width: 90px; height: 90px; margin-top: 70px; margin-bottom: 25px; margin-right: 130px;" src="~/Images/flat.png" />
                </p>
            </a>
        </div>
        <div class="card mb-4 box-shadow card-1" style="min-width: 280px; height: 400px; max-height: 400px; background-color: rgb(62, 142, 201); width: 300px; cursor: pointer">
            <a href=@Url.Action("SignUp", "Account")>
                <div class="card-body" style="color: white;">
                    <span style="float: left; margin-bottom: 20px; margin-left: 0; font-size: 24px; font-weight: bold; text-align: left;">Регистрация</span>
                    <span style="float: left; font-size: 21px; margin-left: 0; text-align: left; margin-bottom: 5px;"> 
                        Вход в систему позволит покупать подписки и добавлять заявки на объявления
                    </span>
                </div>
                <p >
                    <img class="icon" style="width: 90px; height: 90px; margin-top: 35px; margin-bottom: 25px; margin-right: 130px;" src="~/Images/shield.png"/>
                </p>
            </a>
        </div>
        <div class="card mb-4 box-shadow  card-1" style="min-width: 280px; max-height: 400px; background-color: rgb(255, 158, 89); width: 300px; cursor: pointer">
            <a href=@Url.Action("News", "Home")>
                <div class="card-body" style="color: white;">
                    <span style="float: left; margin-bottom: 20px; margin-left: 0; font-size: 24px; font-weight: bold;">Новости и акции</span>
                    <span style="float: left; font-size: 21px; margin-left: 0; text-align: left; margin-bottom: 5px;">Следите за интересными новостями и акциями.</span>
                </div>
                <p> <img class="icon" style="width: 90px; height: 90px; margin-top: 100px; margin-bottom: 25px; margin-right: 130px;" src="~/Images/gift.png" /></p>
            </a>
        </div>
    </div>
</div>

Square.UI/Views/Home/Policy.cshtml
@model string
@{
    ViewBag.Title = "Policy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container" style="width: 70%; margin: 0 auto; margin-top: 30px;">
    <h2>Политика в отношении обработки персональных данных</h2>
    <p>@Model</p>
</div>

Square.UI/Views/Home/SecurityPayment.cshtml
@{
    ViewBag.Title = "SecurityPayment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .descr {
       margin-top: 50px;
        margin-bottom: 50px;

    }

    
    @@media only screen and (max-width: 800px) {
        .descr {
            margin-top: 10px;
        }
    }
</style>
<div class="container my-5 z-depth-1">


    <!--Section: Content-->
    <section class="dark-grey-text">

        <div class="row pr-lg-5">
            <div class="col-md-7 mb-5" >

                <div class="view">
                    <img src="~/Images/securityPayment.jpg" class="img-fluid" alt="smaple image" />
                </div>

            </div>
            <div class="col-md-5 d-flex align-items-center my-content">
                <div class="descr">

                    <h3 class="font-weight-bold mb-4">Безопасная оплата!</h3>

                    <p>
                        Никто не узнает данные вашей карты: оплата пройдёт через АО «АЛЬФА-БАНК».
                        К оплате принимаются карты VISA, MasterCard, МИР.
                    </p>
                    <ul class="list-unstyled list-inline " style="   margin-bottom: 0px;">
                        <li class="payType list-inline-item">
                            <img style="width: 50px; margin-right: 5px; margin-top: 2px" src="~/Images/payment/15.png" />
                            <img style="width: 50px; margin-right: 5px; margin-top: 2px" src="~/Images/payment/16.png" />
                            <img style="width: 50px; margin-right: 5px; margin-top: 2px" src="~/Images/payment/18.png" />
                        </li>
                    </ul>
                    <br />
                    <p>
                        Услуга оплаты через интернет осуществляется в соответствии с Правилами международных платежных
                        систем Visa, MasterCard и Платежной системы МИР
                        на принципах соблюдения конфиденциальности и безопасности совершения платежа,
                        для чего используются самые современные методы проверки, шифрования и передачи данных по закрытым каналам связи.
                        Ввод данных банковской карты осуществляется на защищенной платежной странице АО «АЛЬФА-БАНК».
                    </p>

                    <a class="btn btn-light-green btn-rounded mx-0" href=@Url.Action("Index", "Price")>Приобрести подписку</a>
                </div>
            </div>
        </div>

    </section>
    <!--Section: Content-->


</div>